begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/*  * Copyright (C) 2004 IBM Corporation  * Authors:  * Leendert van Doorn<leendert@watson.ibm.com>  * Dave Safford<safford@watson.ibm.com>  * Reiner Sailer<sailer@watson.ibm.com>  * Kylene Hall<kjhall@us.ibm.com>  *  * Copyright (C) 2013 Obsidian Research Corp  * Jason Gunthorpe<jgunthorpe@obsidianresearch.com>  *  * Device file system interface to the TPM  *  * This program is free software; you can redistribute it and/or  * modify it under the terms of the GNU General Public License as  * published by the Free Software Foundation, version 2 of the  * License.  *  */
end_comment

begin_include
include|#
directive|include
file|<linux/slab.h>
end_include

begin_include
include|#
directive|include
file|<linux/uaccess.h>
end_include

begin_include
include|#
directive|include
file|"tpm.h"
end_include

begin_struct
DECL|struct|file_priv
struct|struct
name|file_priv
block|{
DECL|member|chip
name|struct
name|tpm_chip
modifier|*
name|chip
decl_stmt|;
comment|/* Data passed to and from the tpm via the read/write calls */
DECL|member|data_pending
name|atomic_t
name|data_pending
decl_stmt|;
DECL|member|buffer_mutex
name|struct
name|mutex
name|buffer_mutex
decl_stmt|;
DECL|member|user_read_timer
name|struct
name|timer_list
name|user_read_timer
decl_stmt|;
comment|/* user needs to claim result */
DECL|member|work
name|struct
name|work_struct
name|work
decl_stmt|;
DECL|member|data_buffer
name|u8
name|data_buffer
index|[
name|TPM_BUFSIZE
index|]
decl_stmt|;
block|}
struct|;
end_struct

begin_function
DECL|function|user_reader_timeout (unsigned long ptr)
specifier|static
name|void
name|user_reader_timeout
parameter_list|(
name|unsigned
name|long
name|ptr
parameter_list|)
block|{
name|struct
name|file_priv
modifier|*
name|priv
init|=
operator|(
expr|struct
name|file_priv
operator|*
operator|)
name|ptr
decl_stmt|;
name|pr_warn
argument_list|(
literal|"TPM user space timeout is deprecated (pid=%d)\n"
argument_list|,
name|task_tgid_nr
argument_list|(
name|current
argument_list|)
argument_list|)
expr_stmt|;
name|schedule_work
argument_list|(
operator|&
name|priv
operator|->
name|work
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
DECL|function|timeout_work (struct work_struct * work)
specifier|static
name|void
name|timeout_work
parameter_list|(
name|struct
name|work_struct
modifier|*
name|work
parameter_list|)
block|{
name|struct
name|file_priv
modifier|*
name|priv
init|=
name|container_of
argument_list|(
name|work
argument_list|,
expr|struct
name|file_priv
argument_list|,
name|work
argument_list|)
decl_stmt|;
name|mutex_lock
argument_list|(
operator|&
name|priv
operator|->
name|buffer_mutex
argument_list|)
expr_stmt|;
name|atomic_set
argument_list|(
operator|&
name|priv
operator|->
name|data_pending
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|memset
argument_list|(
name|priv
operator|->
name|data_buffer
argument_list|,
literal|0
argument_list|,
sizeof|sizeof
argument_list|(
name|priv
operator|->
name|data_buffer
argument_list|)
argument_list|)
expr_stmt|;
name|mutex_unlock
argument_list|(
operator|&
name|priv
operator|->
name|buffer_mutex
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
DECL|function|tpm_open (struct inode * inode,struct file * file)
specifier|static
name|int
name|tpm_open
parameter_list|(
name|struct
name|inode
modifier|*
name|inode
parameter_list|,
name|struct
name|file
modifier|*
name|file
parameter_list|)
block|{
name|struct
name|tpm_chip
modifier|*
name|chip
init|=
name|container_of
argument_list|(
name|inode
operator|->
name|i_cdev
argument_list|,
expr|struct
name|tpm_chip
argument_list|,
name|cdev
argument_list|)
decl_stmt|;
name|struct
name|file_priv
modifier|*
name|priv
decl_stmt|;
comment|/* It's assured that the chip will be opened just once, 	 * by the check of is_open variable, which is protected 	 * by driver_lock. */
if|if
condition|(
name|test_and_set_bit
argument_list|(
literal|0
argument_list|,
operator|&
name|chip
operator|->
name|is_open
argument_list|)
condition|)
block|{
name|dev_dbg
argument_list|(
operator|&
name|chip
operator|->
name|dev
argument_list|,
literal|"Another process owns this TPM\n"
argument_list|)
expr_stmt|;
return|return
operator|-
name|EBUSY
return|;
block|}
name|priv
operator|=
name|kzalloc
argument_list|(
sizeof|sizeof
argument_list|(
operator|*
name|priv
argument_list|)
argument_list|,
name|GFP_KERNEL
argument_list|)
expr_stmt|;
if|if
condition|(
name|priv
operator|==
name|NULL
condition|)
block|{
name|clear_bit
argument_list|(
literal|0
argument_list|,
operator|&
name|chip
operator|->
name|is_open
argument_list|)
expr_stmt|;
return|return
operator|-
name|ENOMEM
return|;
block|}
name|priv
operator|->
name|chip
operator|=
name|chip
expr_stmt|;
name|atomic_set
argument_list|(
operator|&
name|priv
operator|->
name|data_pending
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|mutex_init
argument_list|(
operator|&
name|priv
operator|->
name|buffer_mutex
argument_list|)
expr_stmt|;
name|setup_timer
argument_list|(
operator|&
name|priv
operator|->
name|user_read_timer
argument_list|,
name|user_reader_timeout
argument_list|,
operator|(
name|unsigned
name|long
operator|)
name|priv
argument_list|)
expr_stmt|;
name|INIT_WORK
argument_list|(
operator|&
name|priv
operator|->
name|work
argument_list|,
name|timeout_work
argument_list|)
expr_stmt|;
name|file
operator|->
name|private_data
operator|=
name|priv
expr_stmt|;
return|return
literal|0
return|;
block|}
end_function

begin_function
DECL|function|tpm_read (struct file * file,char __user * buf,size_t size,loff_t * off)
specifier|static
name|ssize_t
name|tpm_read
parameter_list|(
name|struct
name|file
modifier|*
name|file
parameter_list|,
name|char
name|__user
modifier|*
name|buf
parameter_list|,
name|size_t
name|size
parameter_list|,
name|loff_t
modifier|*
name|off
parameter_list|)
block|{
name|struct
name|file_priv
modifier|*
name|priv
init|=
name|file
operator|->
name|private_data
decl_stmt|;
name|ssize_t
name|ret_size
decl_stmt|;
name|int
name|rc
decl_stmt|;
name|del_singleshot_timer_sync
argument_list|(
operator|&
name|priv
operator|->
name|user_read_timer
argument_list|)
expr_stmt|;
name|flush_work
argument_list|(
operator|&
name|priv
operator|->
name|work
argument_list|)
expr_stmt|;
name|ret_size
operator|=
name|atomic_read
argument_list|(
operator|&
name|priv
operator|->
name|data_pending
argument_list|)
expr_stmt|;
if|if
condition|(
name|ret_size
operator|>
literal|0
condition|)
block|{
comment|/* relay data */
name|ssize_t
name|orig_ret_size
init|=
name|ret_size
decl_stmt|;
if|if
condition|(
name|size
operator|<
name|ret_size
condition|)
name|ret_size
operator|=
name|size
expr_stmt|;
name|mutex_lock
argument_list|(
operator|&
name|priv
operator|->
name|buffer_mutex
argument_list|)
expr_stmt|;
name|rc
operator|=
name|copy_to_user
argument_list|(
name|buf
argument_list|,
name|priv
operator|->
name|data_buffer
argument_list|,
name|ret_size
argument_list|)
expr_stmt|;
name|memset
argument_list|(
name|priv
operator|->
name|data_buffer
argument_list|,
literal|0
argument_list|,
name|orig_ret_size
argument_list|)
expr_stmt|;
if|if
condition|(
name|rc
condition|)
name|ret_size
operator|=
operator|-
name|EFAULT
expr_stmt|;
name|mutex_unlock
argument_list|(
operator|&
name|priv
operator|->
name|buffer_mutex
argument_list|)
expr_stmt|;
block|}
name|atomic_set
argument_list|(
operator|&
name|priv
operator|->
name|data_pending
argument_list|,
literal|0
argument_list|)
expr_stmt|;
return|return
name|ret_size
return|;
block|}
end_function

begin_function
DECL|function|tpm_write (struct file * file,const char __user * buf,size_t size,loff_t * off)
specifier|static
name|ssize_t
name|tpm_write
parameter_list|(
name|struct
name|file
modifier|*
name|file
parameter_list|,
specifier|const
name|char
name|__user
modifier|*
name|buf
parameter_list|,
name|size_t
name|size
parameter_list|,
name|loff_t
modifier|*
name|off
parameter_list|)
block|{
name|struct
name|file_priv
modifier|*
name|priv
init|=
name|file
operator|->
name|private_data
decl_stmt|;
name|size_t
name|in_size
init|=
name|size
decl_stmt|;
name|ssize_t
name|out_size
decl_stmt|;
comment|/* cannot perform a write until the read has cleared 	   either via tpm_read or a user_read_timer timeout. 	   This also prevents splitted buffered writes from blocking here. 	*/
if|if
condition|(
name|atomic_read
argument_list|(
operator|&
name|priv
operator|->
name|data_pending
argument_list|)
operator|!=
literal|0
condition|)
return|return
operator|-
name|EBUSY
return|;
if|if
condition|(
name|in_size
operator|>
name|TPM_BUFSIZE
condition|)
return|return
operator|-
name|E2BIG
return|;
name|mutex_lock
argument_list|(
operator|&
name|priv
operator|->
name|buffer_mutex
argument_list|)
expr_stmt|;
if|if
condition|(
name|copy_from_user
argument_list|(
name|priv
operator|->
name|data_buffer
argument_list|,
operator|(
name|void
name|__user
operator|*
operator|)
name|buf
argument_list|,
name|in_size
argument_list|)
condition|)
block|{
name|mutex_unlock
argument_list|(
operator|&
name|priv
operator|->
name|buffer_mutex
argument_list|)
expr_stmt|;
return|return
operator|-
name|EFAULT
return|;
block|}
comment|/* atomic tpm command send and result receive. We only hold the ops 	 * lock during this period so that the tpm can be unregistered even if 	 * the char dev is held open. 	 */
if|if
condition|(
name|tpm_try_get_ops
argument_list|(
name|priv
operator|->
name|chip
argument_list|)
condition|)
block|{
name|mutex_unlock
argument_list|(
operator|&
name|priv
operator|->
name|buffer_mutex
argument_list|)
expr_stmt|;
return|return
operator|-
name|EPIPE
return|;
block|}
name|out_size
operator|=
name|tpm_transmit
argument_list|(
name|priv
operator|->
name|chip
argument_list|,
name|NULL
argument_list|,
name|priv
operator|->
name|data_buffer
argument_list|,
sizeof|sizeof
argument_list|(
name|priv
operator|->
name|data_buffer
argument_list|)
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|tpm_put_ops
argument_list|(
name|priv
operator|->
name|chip
argument_list|)
expr_stmt|;
if|if
condition|(
name|out_size
operator|<
literal|0
condition|)
block|{
name|mutex_unlock
argument_list|(
operator|&
name|priv
operator|->
name|buffer_mutex
argument_list|)
expr_stmt|;
return|return
name|out_size
return|;
block|}
name|atomic_set
argument_list|(
operator|&
name|priv
operator|->
name|data_pending
argument_list|,
name|out_size
argument_list|)
expr_stmt|;
name|mutex_unlock
argument_list|(
operator|&
name|priv
operator|->
name|buffer_mutex
argument_list|)
expr_stmt|;
comment|/* Set a timeout by which the reader must come claim the result */
name|mod_timer
argument_list|(
operator|&
name|priv
operator|->
name|user_read_timer
argument_list|,
name|jiffies
operator|+
operator|(
literal|120
operator|*
name|HZ
operator|)
argument_list|)
expr_stmt|;
return|return
name|in_size
return|;
block|}
end_function

begin_comment
comment|/*  * Called on file close  */
end_comment

begin_function
DECL|function|tpm_release (struct inode * inode,struct file * file)
specifier|static
name|int
name|tpm_release
parameter_list|(
name|struct
name|inode
modifier|*
name|inode
parameter_list|,
name|struct
name|file
modifier|*
name|file
parameter_list|)
block|{
name|struct
name|file_priv
modifier|*
name|priv
init|=
name|file
operator|->
name|private_data
decl_stmt|;
name|del_singleshot_timer_sync
argument_list|(
operator|&
name|priv
operator|->
name|user_read_timer
argument_list|)
expr_stmt|;
name|flush_work
argument_list|(
operator|&
name|priv
operator|->
name|work
argument_list|)
expr_stmt|;
name|file
operator|->
name|private_data
operator|=
name|NULL
expr_stmt|;
name|atomic_set
argument_list|(
operator|&
name|priv
operator|->
name|data_pending
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|clear_bit
argument_list|(
literal|0
argument_list|,
operator|&
name|priv
operator|->
name|chip
operator|->
name|is_open
argument_list|)
expr_stmt|;
name|kfree
argument_list|(
name|priv
argument_list|)
expr_stmt|;
return|return
literal|0
return|;
block|}
end_function

begin_decl_stmt
DECL|variable|tpm_fops
specifier|const
name|struct
name|file_operations
name|tpm_fops
init|=
block|{
operator|.
name|owner
operator|=
name|THIS_MODULE
block|,
operator|.
name|llseek
operator|=
name|no_llseek
block|,
operator|.
name|open
operator|=
name|tpm_open
block|,
operator|.
name|read
operator|=
name|tpm_read
block|,
operator|.
name|write
operator|=
name|tpm_write
block|,
operator|.
name|release
operator|=
name|tpm_release
block|, }
decl_stmt|;
end_decl_stmt

end_unit

