begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/*  * Copyright (C) 2004 IBM Corporation  * Authors:  * Leendert van Doorn<leendert@watson.ibm.com>  * Dave Safford<safford@watson.ibm.com>  * Reiner Sailer<sailer@watson.ibm.com>  * Kylene Hall<kjhall@us.ibm.com>  *  * Copyright (C) 2013 Obsidian Research Corp  * Jason Gunthorpe<jgunthorpe@obsidianresearch.com>  *  * Device file system interface to the TPM  *  * This program is free software; you can redistribute it and/or  * modify it under the terms of the GNU General Public License as  * published by the Free Software Foundation, version 2 of the  * License.  *  */
end_comment

begin_include
include|#
directive|include
file|<linux/slab.h>
end_include

begin_include
include|#
directive|include
file|<linux/uaccess.h>
end_include

begin_include
include|#
directive|include
file|"tpm.h"
end_include

begin_include
include|#
directive|include
file|"tpm-dev.h"
end_include

begin_function
DECL|function|user_reader_timeout (struct timer_list * t)
specifier|static
name|void
name|user_reader_timeout
parameter_list|(
name|struct
name|timer_list
modifier|*
name|t
parameter_list|)
block|{
name|struct
name|file_priv
modifier|*
name|priv
init|=
name|from_timer
argument_list|(
name|priv
argument_list|,
name|t
argument_list|,
name|user_read_timer
argument_list|)
decl_stmt|;
name|pr_warn
argument_list|(
literal|"TPM user space timeout is deprecated (pid=%d)\n"
argument_list|,
name|task_tgid_nr
argument_list|(
name|current
argument_list|)
argument_list|)
expr_stmt|;
name|schedule_work
argument_list|(
operator|&
name|priv
operator|->
name|work
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
DECL|function|timeout_work (struct work_struct * work)
specifier|static
name|void
name|timeout_work
parameter_list|(
name|struct
name|work_struct
modifier|*
name|work
parameter_list|)
block|{
name|struct
name|file_priv
modifier|*
name|priv
init|=
name|container_of
argument_list|(
name|work
argument_list|,
expr|struct
name|file_priv
argument_list|,
name|work
argument_list|)
decl_stmt|;
name|mutex_lock
argument_list|(
operator|&
name|priv
operator|->
name|buffer_mutex
argument_list|)
expr_stmt|;
name|atomic_set
argument_list|(
operator|&
name|priv
operator|->
name|data_pending
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|memset
argument_list|(
name|priv
operator|->
name|data_buffer
argument_list|,
literal|0
argument_list|,
sizeof|sizeof
argument_list|(
name|priv
operator|->
name|data_buffer
argument_list|)
argument_list|)
expr_stmt|;
name|mutex_unlock
argument_list|(
operator|&
name|priv
operator|->
name|buffer_mutex
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
DECL|function|tpm_common_open (struct file * file,struct tpm_chip * chip,struct file_priv * priv)
name|void
name|tpm_common_open
parameter_list|(
name|struct
name|file
modifier|*
name|file
parameter_list|,
name|struct
name|tpm_chip
modifier|*
name|chip
parameter_list|,
name|struct
name|file_priv
modifier|*
name|priv
parameter_list|)
block|{
name|priv
operator|->
name|chip
operator|=
name|chip
expr_stmt|;
name|atomic_set
argument_list|(
operator|&
name|priv
operator|->
name|data_pending
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|mutex_init
argument_list|(
operator|&
name|priv
operator|->
name|buffer_mutex
argument_list|)
expr_stmt|;
name|timer_setup
argument_list|(
operator|&
name|priv
operator|->
name|user_read_timer
argument_list|,
name|user_reader_timeout
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|INIT_WORK
argument_list|(
operator|&
name|priv
operator|->
name|work
argument_list|,
name|timeout_work
argument_list|)
expr_stmt|;
name|file
operator|->
name|private_data
operator|=
name|priv
expr_stmt|;
block|}
end_function

begin_function
DECL|function|tpm_common_read (struct file * file,char __user * buf,size_t size,loff_t * off)
name|ssize_t
name|tpm_common_read
parameter_list|(
name|struct
name|file
modifier|*
name|file
parameter_list|,
name|char
name|__user
modifier|*
name|buf
parameter_list|,
name|size_t
name|size
parameter_list|,
name|loff_t
modifier|*
name|off
parameter_list|)
block|{
name|struct
name|file_priv
modifier|*
name|priv
init|=
name|file
operator|->
name|private_data
decl_stmt|;
name|ssize_t
name|ret_size
decl_stmt|;
name|ssize_t
name|orig_ret_size
decl_stmt|;
name|int
name|rc
decl_stmt|;
name|del_singleshot_timer_sync
argument_list|(
operator|&
name|priv
operator|->
name|user_read_timer
argument_list|)
expr_stmt|;
name|flush_work
argument_list|(
operator|&
name|priv
operator|->
name|work
argument_list|)
expr_stmt|;
name|ret_size
operator|=
name|atomic_read
argument_list|(
operator|&
name|priv
operator|->
name|data_pending
argument_list|)
expr_stmt|;
if|if
condition|(
name|ret_size
operator|>
literal|0
condition|)
block|{
comment|/* relay data */
name|orig_ret_size
operator|=
name|ret_size
expr_stmt|;
if|if
condition|(
name|size
operator|<
name|ret_size
condition|)
name|ret_size
operator|=
name|size
expr_stmt|;
name|mutex_lock
argument_list|(
operator|&
name|priv
operator|->
name|buffer_mutex
argument_list|)
expr_stmt|;
name|rc
operator|=
name|copy_to_user
argument_list|(
name|buf
argument_list|,
name|priv
operator|->
name|data_buffer
argument_list|,
name|ret_size
argument_list|)
expr_stmt|;
name|memset
argument_list|(
name|priv
operator|->
name|data_buffer
argument_list|,
literal|0
argument_list|,
name|orig_ret_size
argument_list|)
expr_stmt|;
if|if
condition|(
name|rc
condition|)
name|ret_size
operator|=
operator|-
name|EFAULT
expr_stmt|;
name|mutex_unlock
argument_list|(
operator|&
name|priv
operator|->
name|buffer_mutex
argument_list|)
expr_stmt|;
block|}
name|atomic_set
argument_list|(
operator|&
name|priv
operator|->
name|data_pending
argument_list|,
literal|0
argument_list|)
expr_stmt|;
return|return
name|ret_size
return|;
block|}
end_function

begin_function
DECL|function|tpm_common_write (struct file * file,const char __user * buf,size_t size,loff_t * off,struct tpm_space * space)
name|ssize_t
name|tpm_common_write
parameter_list|(
name|struct
name|file
modifier|*
name|file
parameter_list|,
specifier|const
name|char
name|__user
modifier|*
name|buf
parameter_list|,
name|size_t
name|size
parameter_list|,
name|loff_t
modifier|*
name|off
parameter_list|,
name|struct
name|tpm_space
modifier|*
name|space
parameter_list|)
block|{
name|struct
name|file_priv
modifier|*
name|priv
init|=
name|file
operator|->
name|private_data
decl_stmt|;
name|size_t
name|in_size
init|=
name|size
decl_stmt|;
name|ssize_t
name|out_size
decl_stmt|;
comment|/* Cannot perform a write until the read has cleared either via 	 * tpm_read or a user_read_timer timeout. This also prevents split 	 * buffered writes from blocking here. 	 */
if|if
condition|(
name|atomic_read
argument_list|(
operator|&
name|priv
operator|->
name|data_pending
argument_list|)
operator|!=
literal|0
condition|)
return|return
operator|-
name|EBUSY
return|;
if|if
condition|(
name|in_size
operator|>
name|TPM_BUFSIZE
condition|)
return|return
operator|-
name|E2BIG
return|;
name|mutex_lock
argument_list|(
operator|&
name|priv
operator|->
name|buffer_mutex
argument_list|)
expr_stmt|;
if|if
condition|(
name|copy_from_user
argument_list|(
name|priv
operator|->
name|data_buffer
argument_list|,
operator|(
name|void
name|__user
operator|*
operator|)
name|buf
argument_list|,
name|in_size
argument_list|)
condition|)
block|{
name|mutex_unlock
argument_list|(
operator|&
name|priv
operator|->
name|buffer_mutex
argument_list|)
expr_stmt|;
return|return
operator|-
name|EFAULT
return|;
block|}
if|if
condition|(
name|in_size
operator|<
literal|6
operator|||
name|in_size
operator|<
name|be32_to_cpu
argument_list|(
operator|*
operator|(
operator|(
name|__be32
operator|*
operator|)
operator|(
name|priv
operator|->
name|data_buffer
operator|+
literal|2
operator|)
operator|)
argument_list|)
condition|)
block|{
name|mutex_unlock
argument_list|(
operator|&
name|priv
operator|->
name|buffer_mutex
argument_list|)
expr_stmt|;
return|return
operator|-
name|EINVAL
return|;
block|}
comment|/* atomic tpm command send and result receive. We only hold the ops 	 * lock during this period so that the tpm can be unregistered even if 	 * the char dev is held open. 	 */
if|if
condition|(
name|tpm_try_get_ops
argument_list|(
name|priv
operator|->
name|chip
argument_list|)
condition|)
block|{
name|mutex_unlock
argument_list|(
operator|&
name|priv
operator|->
name|buffer_mutex
argument_list|)
expr_stmt|;
return|return
operator|-
name|EPIPE
return|;
block|}
name|out_size
operator|=
name|tpm_transmit
argument_list|(
name|priv
operator|->
name|chip
argument_list|,
name|space
argument_list|,
name|priv
operator|->
name|data_buffer
argument_list|,
sizeof|sizeof
argument_list|(
name|priv
operator|->
name|data_buffer
argument_list|)
argument_list|,
literal|0
argument_list|)
expr_stmt|;
name|tpm_put_ops
argument_list|(
name|priv
operator|->
name|chip
argument_list|)
expr_stmt|;
if|if
condition|(
name|out_size
operator|<
literal|0
condition|)
block|{
name|mutex_unlock
argument_list|(
operator|&
name|priv
operator|->
name|buffer_mutex
argument_list|)
expr_stmt|;
return|return
name|out_size
return|;
block|}
name|atomic_set
argument_list|(
operator|&
name|priv
operator|->
name|data_pending
argument_list|,
name|out_size
argument_list|)
expr_stmt|;
name|mutex_unlock
argument_list|(
operator|&
name|priv
operator|->
name|buffer_mutex
argument_list|)
expr_stmt|;
comment|/* Set a timeout by which the reader must come claim the result */
name|mod_timer
argument_list|(
operator|&
name|priv
operator|->
name|user_read_timer
argument_list|,
name|jiffies
operator|+
operator|(
literal|120
operator|*
name|HZ
operator|)
argument_list|)
expr_stmt|;
return|return
name|in_size
return|;
block|}
end_function

begin_comment
comment|/*  * Called on file close  */
end_comment

begin_function
DECL|function|tpm_common_release (struct file * file,struct file_priv * priv)
name|void
name|tpm_common_release
parameter_list|(
name|struct
name|file
modifier|*
name|file
parameter_list|,
name|struct
name|file_priv
modifier|*
name|priv
parameter_list|)
block|{
name|del_singleshot_timer_sync
argument_list|(
operator|&
name|priv
operator|->
name|user_read_timer
argument_list|)
expr_stmt|;
name|flush_work
argument_list|(
operator|&
name|priv
operator|->
name|work
argument_list|)
expr_stmt|;
name|file
operator|->
name|private_data
operator|=
name|NULL
expr_stmt|;
name|atomic_set
argument_list|(
operator|&
name|priv
operator|->
name|data_pending
argument_list|,
literal|0
argument_list|)
expr_stmt|;
block|}
end_function

end_unit

