begin_unit|revision:0.9.5;language:C;cregit-version:0.0.1
begin_comment
comment|/*  * Copyright (C) 2004 IBM Corporation  * Authors:  * Leendert van Doorn<leendert@watson.ibm.com>  * Dave Safford<safford@watson.ibm.com>  * Reiner Sailer<sailer@watson.ibm.com>  * Kylene Hall<kjhall@us.ibm.com>  *  * Copyright (C) 2013 Obsidian Research Corp  * Jason Gunthorpe<jgunthorpe@obsidianresearch.com>  *  * Device file system interface to the TPM  *  * This program is free software; you can redistribute it and/or  * modify it under the terms of the GNU General Public License as  * published by the Free Software Foundation, version 2 of the  * License.  *  */
end_comment

begin_include
include|#
directive|include
file|<linux/slab.h>
end_include

begin_include
include|#
directive|include
file|"tpm-dev.h"
end_include

begin_function
DECL|function|tpm_open (struct inode * inode,struct file * file)
specifier|static
name|int
name|tpm_open
parameter_list|(
name|struct
name|inode
modifier|*
name|inode
parameter_list|,
name|struct
name|file
modifier|*
name|file
parameter_list|)
block|{
name|struct
name|tpm_chip
modifier|*
name|chip
decl_stmt|;
name|struct
name|file_priv
modifier|*
name|priv
decl_stmt|;
name|chip
operator|=
name|container_of
argument_list|(
name|inode
operator|->
name|i_cdev
argument_list|,
expr|struct
name|tpm_chip
argument_list|,
name|cdev
argument_list|)
expr_stmt|;
comment|/* It's assured that the chip will be opened just once, 	 * by the check of is_open variable, which is protected 	 * by driver_lock. */
if|if
condition|(
name|test_and_set_bit
argument_list|(
literal|0
argument_list|,
operator|&
name|chip
operator|->
name|is_open
argument_list|)
condition|)
block|{
name|dev_dbg
argument_list|(
operator|&
name|chip
operator|->
name|dev
argument_list|,
literal|"Another process owns this TPM\n"
argument_list|)
expr_stmt|;
return|return
operator|-
name|EBUSY
return|;
block|}
name|priv
operator|=
name|kzalloc
argument_list|(
sizeof|sizeof
argument_list|(
operator|*
name|priv
argument_list|)
argument_list|,
name|GFP_KERNEL
argument_list|)
expr_stmt|;
if|if
condition|(
name|priv
operator|==
name|NULL
condition|)
goto|goto
name|out
goto|;
name|tpm_common_open
argument_list|(
name|file
argument_list|,
name|chip
argument_list|,
name|priv
argument_list|)
expr_stmt|;
return|return
literal|0
return|;
name|out
label|:
name|clear_bit
argument_list|(
literal|0
argument_list|,
operator|&
name|chip
operator|->
name|is_open
argument_list|)
expr_stmt|;
return|return
operator|-
name|ENOMEM
return|;
block|}
end_function

begin_function
DECL|function|tpm_write (struct file * file,const char __user * buf,size_t size,loff_t * off)
specifier|static
name|ssize_t
name|tpm_write
parameter_list|(
name|struct
name|file
modifier|*
name|file
parameter_list|,
specifier|const
name|char
name|__user
modifier|*
name|buf
parameter_list|,
name|size_t
name|size
parameter_list|,
name|loff_t
modifier|*
name|off
parameter_list|)
block|{
return|return
name|tpm_common_write
argument_list|(
name|file
argument_list|,
name|buf
argument_list|,
name|size
argument_list|,
name|off
argument_list|,
name|NULL
argument_list|)
return|;
block|}
end_function

begin_comment
comment|/*  * Called on file close  */
end_comment

begin_function
DECL|function|tpm_release (struct inode * inode,struct file * file)
specifier|static
name|int
name|tpm_release
parameter_list|(
name|struct
name|inode
modifier|*
name|inode
parameter_list|,
name|struct
name|file
modifier|*
name|file
parameter_list|)
block|{
name|struct
name|file_priv
modifier|*
name|priv
init|=
name|file
operator|->
name|private_data
decl_stmt|;
name|tpm_common_release
argument_list|(
name|file
argument_list|,
name|priv
argument_list|)
expr_stmt|;
name|clear_bit
argument_list|(
literal|0
argument_list|,
operator|&
name|priv
operator|->
name|chip
operator|->
name|is_open
argument_list|)
expr_stmt|;
name|kfree
argument_list|(
name|priv
argument_list|)
expr_stmt|;
return|return
literal|0
return|;
block|}
end_function

begin_decl_stmt
DECL|variable|tpm_fops
specifier|const
name|struct
name|file_operations
name|tpm_fops
init|=
block|{
operator|.
name|owner
operator|=
name|THIS_MODULE
block|,
operator|.
name|llseek
operator|=
name|no_llseek
block|,
operator|.
name|open
operator|=
name|tpm_open
block|,
operator|.
name|read
operator|=
name|tpm_common_read
block|,
operator|.
name|write
operator|=
name|tpm_write
block|,
operator|.
name|release
operator|=
name|tpm_release
block|, }
decl_stmt|;
end_decl_stmt

end_unit

